{
 "title": "Kube api server",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(admission_quota_controller_queue_latency{job=\"kube-apiserver\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=\"kube-apiserver\"})"
    }
   ]
  },
  {
   "title": "RPC rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{job=\"kube-apiserver\",instance=~\"$instance\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(apiserver_request_count{job=\"kube-apiserver\",instance=~\"$instance\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(apiserver_request_count{job=\"kube-apiserver\",instance=~\"$instance\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(apiserver_request_count{job=\"kube-apiserver\",instance=~\"$instance\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_latencies_bucket{job=\"kube-apiserver\",instance=~\"$instance\"}[5m])) by (verb, le))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Admission Controller Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(admission_quota_controller_depth{job=\"kube-apiserver\",instance=~\"$instance\",}[5m]))",
     "legendFormat": "depth"
    }
   ]
  },
  {
   "title": "Admission Controller Queue Add Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(admission_quota_controller_adds{job=\"kube-apiserver\",instance=~\"$instance\",}[5m]))",
     "legendFormat": "add"
    }
   ]
  },
  {
   "title": "Admission Controller Queue Latency 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "admission_quota_controller_queue_latency{job=\"kube-apiserver\",quantile=\"0.99\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ETCD Cache entry count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_helper_cache_entry_count{job=\"kube-apiserver\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ETCD Cache Hit rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_helper_cache_hit_count{job=\"kube-apiserver\",instance=~\"$instance\"}[5m])",
     "legendFormat": "hit {{instance}}"
    },
    {
     "expr": "rate(etcd_helper_cache_miss_count{job=\"kube-apiserver\",instance=~\"$instance\"}[5m])",
     "legendFormat": "miss {{instance}}"
    }
   ]
  },
  {
   "title": "ETCD Cache Latency 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "etcd_request_cache_get_latencies_summary{job=\"kube-apiserver\",instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "get {{instance}}"
    },
    {
     "expr": "etcd_request_cache_add_latencies_summary{job=\"kube-apiserver\",instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "add {{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kube-apiserver\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kube-apiserver\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"kube-apiserver\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}