{
 "title": "Kube controller manager",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(deployment_adds{job=\"kube-controller-manager\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=\"kube-controller-manager\"})"
    }
   ]
  },
  {
   "title": "Object Queue add rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(daemonset_adds{job=\"kube-controller-manager\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "daemonset"
    },
    {
     "expr": "sum(rate(deployment_adds{job=\"kube-controller-manager\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "deployment"
    },
    {
     "expr": "sum(rate(job_adds{job=\"kube-controller-manager\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "job"
    },
    {
     "expr": "sum(rate(replicaset_adds{job=\"kube-controller-manager\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "replicaset"
    },
    {
     "expr": "sum(rate(statefulset_adds{job=\"kube-controller-manager\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "statefulset"
    }
   ]
  },
  {
   "title": "Object Queue depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(daemonset_depth{job=\"kube-controller-manager\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "daemonset"
    },
    {
     "expr": "sum(rate(deployment_depth{job=\"kube-controller-manager\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "deployment"
    },
    {
     "expr": "sum(rate(job_depth{job=\"kube-controller-manager\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "job"
    },
    {
     "expr": "sum(rate(replicaset_depth{job=\"kube-controller-manager\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "replicaset"
    },
    {
     "expr": "sum(rate(statefulset_depth{job=\"kube-controller-manager\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "statefulset"
    }
   ]
  },
  {
   "title": "Object Queue Latency 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "daemonset_queue_latency{job=\"kube-controller-manager\", instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "daemonset {{instance}}"
    },
    {
     "expr": "deployment_queue_latency{job=\"kube-controller-manager\", instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "deployment {{instance}}"
    },
    {
     "expr": "statefulset_queue_latency{job=\"kube-controller-manager\", instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "statefulset  {{instance}}"
    },
    {
     "expr": "replicaset_queue_latency{job=\"kube-controller-manager\", instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "replicaset  {{instance}}"
    },
    {
     "expr": "job_queue_latency{job=\"kube-controller-manager\", instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "job {{instance}}"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-controller-manager\",instance=~\"$instance\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-controller-manager\",instance=~\"$instance\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-controller-manager\",instance=~\"$instance\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-controller-manager\",instance=~\"$instance\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Post Request duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(rest_client_request_latency_seconds_bucket{job=\"kube-controller-manager\",instance=~\"$instance\",verb=\"POST\"}[5m]))",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "GET Request duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(rest_client_request_latency_seconds_bucket{job=\"kube-controller-manager\",instance=~\"$instance\",verb=\"GET\"}[5m]))",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kube-controller-manager\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kube-controller-manager\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"kube-controller-manager\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}